Добавил класс MyStack и сделал в нем события
WhyRocket/my-stack pull request #1
Opened 2024-04-04 12:58 UTC by WhyRocket

2024-04-04 13:09 UTC, aleksandr-goncharov commented
не называй, пожалуйста, ветки миксуя разные конвенции именования, т.е. так не надо **MyStack_Class**. лучше сделать, к примеру, так **my-stack-class**

2024-04-04 13:14 UTC, aleksandr-goncharov requested changes
прочти, пожалуйста, мои вопросы по коду
можешь отвечать в реплаях к ним

2024-04-04 13:14 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    public T? Value
АТД стэк - это коллекция
в данном случае класс MyStack<T> содержит одно свойство Value, которое позволяет хранить одно значение
почему так реализовал?

2024-04-04 13:33 UTC, WhyRocket commented on src/MyStack/MyStack.cs
> +internal class MyStack<T>
Просто оставил значение по умолчанию пока

2024-04-04 13:33 UTC, WhyRocket commented on src/MyStack/MyStack.cs
> +    public event Action<string> OnCompleted;
Поменяю название

2024-04-04 13:38 UTC, WhyRocket commented on src/MyStack/MyStack.cs
> +    public T? Value
Не совсем понял задачу изнначально

2024-04-04 19:26 UTC, aleksandr-goncharov requested changes

2024-04-04 19:26 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    public event Action<string> EventChangeValue;
в названиях ивентов не принято использовать слово "Event", это излишне. вижуалка и так подскажет, что это событие, а не обычное поле

очень часто названия ивентов начинаются со слов "on":

"onCreate"
"onDelete" и т.д.

предлагаю переименовать ивенты, об этом еще ниже напишу

2024-04-04 19:26 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    private T[] Elements { get; set; } = new T[10];
сейчас capasity стэка захардкожено числом 10
было бы хорошо предоставить пользователю возможность передавать capasity в конструктор

также это приватное поле, нужно соблюсти правила именования

также подумай, может стоит объявить это поле как readonly или const? Ведь массив создается единожды и эта переменная в дальнейшем не будет изменяться (будут изменятся только элементы массива)

2024-04-04 19:26 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    public void AddElement(T element)
для стека принято называть метод добавления элемента Push
А метод удаления элемента Pop
Такова традиция, где бы ты ни чтал о стеке - у него всегда будет два метода названные Pop и Push

в соответствии с тем, что метод добавления будет называться Push, подумай о том, как можно было бы назвать event, который возникает при добавлении нового элемента в стэка

ивент, который возникает в случае, когда стэк пуст, я бы назвал так: onEmpty

2024-04-04 19:26 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +        if ((count - 1) == Elements.Length)
когда ты реализуешь методы, мысленно тестируй их

представь, ты создал экземпляр класса MyStack<int>
и теперь вызываешь метод AddElement(5)
что произойдет при вызове этого метода?

2024-04-04 19:26 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +            return;
А зачем здесь ветка else? Здесь в будущем будет какой-то код?

2024-04-04 19:26 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +        Elements[count--] = default(T);
На мой взгляд, декремент и инкремент заставляют много думоть, когда встречаешь их в непростом выражении кода. Нужно вспомнить, про постфиксное и префиксное применение и потратить 2 минуты, чтобы сообразить, как это все будет работать
Я бы написал так: 
Elements[count]=default(T);
count--;

беглого взгляда достаточно, чтобы понять что будет происходить и в какой последовательности. И мозг не напрягся

но воспринимай это скорее, как мое личное мнение, а не рекомендацию))

и действительно ли так необходимо присваивать дефолное значение элементу массива? Вапрос на подумоть

2024-04-07 08:51 UTC, aleksandr-goncharov requested changes
Стек уже оброс функциональностью и выглядит вполне рабочим, это очень хорошо!
Я написал пару комментариев

2024-04-07 08:51 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    public MyStack(int count, int capacity)
не совсем понимаю, для каких целей в конструктор передается параметр count
что означает этот параметр и какой в него закладывается смысл?

2024-04-07 08:51 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +            onPush($"Добавленн элемент: {element}");
что произойдет при попытке выполнения кода
`onPush($"Добавленн элемент: {element}");`
для случая, когда у события onPush нет ни одного подписчика?

2024-04-07 08:51 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +        Elements[Count] = default(T);
думаю, все-таки строчка кода
`Elements[Count] = default(T);`
излишняя
не несет смысловой нагрузки и только увеличивает кол-во кода
можешь вспомнить про бритву Оккама

2024-04-07 08:51 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +        if (Count == 0)
по замыслу событие onEmpty должно возникать в следующем случае: последний элемент из стэка
сейчас событие возникает при попытке удаления элемента из пустого стека
поправь этот момент, пожалуйста

2024-04-07 08:51 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    public int Count { get; private set; } = 0;
тут приваивать нолик бессмысленно)
0 и так - значения полумолчанию для целочисленных типов

2024-04-07 08:51 UTC, aleksandr-goncharov commented on src/MyStack/MyStack.cs
> +    public event Action<string> onPush;
давай немного поразмышляем над типами делегатов, которые используются в ивентах
сейчас для обоих ивентов используется делегат `Action<string>` - функция, которая принимает один строковый параметр и не возвращает параметр. мне кажется, не очень удачно выбран делегат

представь, что ты хочешь подписаться на событие onPush (т.е. событие при собавлении нового элемента в стэк). я бы (как подписчик) хотел получиться в качестве параметра добавленный элемент (а не некую бессмысленную строку). с этим элементом я могу делать все что угодно - например,
- я смогу сделать запись в логе "В стек добавлен элемент 5"
- я могу вывести на консоль сообщение "В стек добавлен элемент 5"

теперь представь, что ты хочешь подписаться на событие onEmpty (событие наступает при удалении последнего элемента из стека, т.е. в ситуации,  когда стек стал пустым). нужно ли тут передавать пользователю некую строку в качестве параметра? какую смысловую нагрузку несет эта строка для подписчика? может быть в данном случае, подойдет такой делегат:
`public delegate void Action();`
это делега не имеющий параметров и возвращаемого значения

2024-04-07 11:33 UTC, aleksandr-goncharov approved these changes

2024-04-07 11:34 UTC, merged