Создал класс MyLinkedStack
WhyRocket/my-stack pull request #24
Opened 2024-04-19 13:50 UTC by WhyRocket

2024-04-19 17:02 UTC, aleksandr-goncharov requested changes

2024-04-19 17:13 UTC, WhyRocket commented on src/MyStack/MyLinkedStack.cs
> +    public int Size { get; private set; }
Ну я назвал исходя из того, что обычно в стеке так называют. Может, оставить?

2024-04-19 17:15 UTC, WhyRocket commented on src/MyStack/MyLinkedStack.cs
> +        public T Value { get; set; } = value;
Init это условно readonly поле, после инициации его нельзя поменять. 
А private set лишь определяет из какой части кода можно будет значение поменять

2024-04-19 17:18 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +    public int Size { get; private set; }
Можно оставить, но тогда неймин должен быть одинаков в обоих списках

2024-04-19 17:19 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +    public int Size { get; private set; }
Иначе возникает вопрос, почему в первом стеке Count, а во втором Size

2024-04-25 15:53 UTC, aleksandr-goncharov requested changes

2024-04-25 15:53 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +    public void Pop()
Pop должен не просто удалить элемент
а еще и вернуть удаленный элемент
и мы вроде в прошлом стеке пробрасывали исключение? может тут его тоже прокинем?

2024-04-25 15:53 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +            throw new InvalidOperationException();
тут бы тоже использовать исключения, которые у нас уже есть

2024-04-26 10:41 UTC, aleksandr-goncharov requested changes

2024-04-26 10:41 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +    public T Pop()
судя по всему, если в стеке представлен один элемент, то метод Pop сгенерирует исключение EmptyMyStackException, а это некорректно

2024-04-26 10:43 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +    public T Pop()
думаю, начало этого метода должно быть аналогично методу Peek:
```
if (_top is null)
{
    throw new EmptyMyStackException();
}
```

2024-04-26 10:44 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +    public T Pop()
еще прошу переименовать переменную temp
например, в node

2024-04-26 14:11 UTC, aleksandr-goncharov requested changes

2024-04-26 14:11 UTC, aleksandr-goncharov commented on src/MyStack/MyLinkedStack.cs
> +        if (_top.Previous is not null)
Если стек пусть, то мы получим в этой строке кода NullReferenceException
когда попробуем через точку получить свойство Previous для поля _top

2024-05-02 08:46 UTC, aleksandr-goncharov approved these changes

2024-05-02 08:46 UTC, merged