Linq tasks
WhyRocket/my-stack pull request #25
Opened 2024-04-25 14:25 UTC by WhyRocket

Написать с использованием методов LINQ запросы и их выполнение

1. Дана целочисленная последовательность. Извлечь из нее все нечетные числа, сохранив их исходный порядок следования и удалив все вхождения повторяющихся элементов, кроме первых.

2. Дана целочисленная последовательность. Извлечь из нее все положительные двузначные числа, отсортировав их по возрастанию.

3. Дана строковая последовательность. Строки последовательности содержат только заглавные буквы латинского алфавита. Отсортировать последовательность по возрастанию длин строк, а строки одинаковой длины – по убыванию.

4. Дана последовательность непустых строк A. Получить последовательность символов, каждый элемент которой является начальным символом соответствующей строки из A. Порядок символов должен быть обратным по отношению к порядку элементов исходной последовательности.

5. Дана целочисленная последовательность. Обрабатывая только положительные числа, получить последовательность их последних цифр и удалить в полученной последовательности все вхождения одинаковых цифр, кроме первого. Порядок полученных цифр должен соответствовать порядку исходных чисел.

6. Дана целочисленная последовательность A. Получить новую последовательность чисел, элементы которой определяются по соответствующим элементам последовательности A следующим образом: если порядковый номер элемента A делится на 3 (3, 6, …), то этот элемент в новую последовательность не включается; если остаток от деления порядкового номера на 3 равен 1 (1, 4, …), то в новую последовательность добавляется удвоенное значение этого элемента; в противном случае (для элементов A с номерами 2, 5, …) элемент добавляется в новую последовательность без изменений. В полученной последовательности сохранить исходный порядок следования элементов.

7. Даны целые числа K1 и K2 и целочисленные последовательности A и B. Получить последовательность, содержащую все числа из A, большие K1, и все числа из B, меньшие K2. Отсортировать полученную последовательность по возрастанию.

8. Даны последовательности положительных целых чисел A и B; все числа в каждой последовательности различны. Найти последовательность всех пар чисел, удовлетворяющих следующим условиям: первый элемент пары принадлежит последовательности A, второй принадлежит B, и оба элемента оканчиваются одной и той же цифрой. Результирующая последовательность называется внутренним объединением последовательностей A и B по ключу, определяемому последними цифрами исходных чисел. Представить найденное объединение в виде последовательности строк, содержащих первый и второй элементы пары, разделенные дефисом, например, «49-129». Порядок следования пар должен определяться исходным порядком элементов последовательности A, а для равных первых элементов – порядком элементов последовательности B.

9. Даны целочисленные последовательности A и B. Получить последовательность всех различных сумм, в которых первое слагаемое берется из A, а второе из B. Упорядочить полученную последовательность по возрастанию

10. Исходная последовательность содержит сведения о клиентах фитнес-центра. Каждый элемент последовательности включает следующие целочисленные поля: <Код клиента>; <Год>; <Номер месяца>; <Продолжительность занятий (в часах)>; Найти элемент последовательности с минимальной продолжительностью занятий. Вывести эту продолжительность, а также соответствующие ей год и номер месяца (в указанном порядке на той же строке). Если имеется несколько элементов с минимальной продолжительностью, то вывести данные того из них, который является последним в исходной последовательности.

2024-04-25 16:06 UTC, aleksandr-goncharov requested changes
ПР большой, это первая часть ревью

2024-04-25 16:06 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +    public static void MyLinkedListLinqDemo()
этот метод тоже не вызывается из Main?

2024-04-25 16:06 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var rnd = new Random();
давай назовем переменную random, а не rnd
rnd не очень хорошее название
можешь освежить в памяти, почитав совершенный код

2024-04-25 16:06 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var list2 = list.Where(x => x % 2 == 0);
тут хочу уточнить, есть ли у тебя понимание того, что Linq работают на основе lazy loading?

2024-04-25 16:06 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var list = new MyLinkedList<int?>();
а почему лист создан от int?
а не просто от int
я не вижу, чтобы ты добавлял в список значения null
может быть это лишнее? а то это приводит к тому, что придется везде писать item.Value, а не просто item

2024-04-25 16:06 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var list3 = list.OrderBy(item => item.Value);
понимаю, что назвать list3 проще
но все-таки было бы хорошо все-таки названия заменить на осмысленные
например, orderedList

2024-04-26 06:01 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var list2 = list.Where(x => x % 2 == 0);
https://metanit.com/sharp/tutorial/15.8.php

2024-04-26 10:03 UTC, WhyRocket commented on src/MyStack/Program.cs
> +        var list2 = list.Where(x => x % 2 == 0);
Ну я догадывался, что LINQ через foreach работает, а запросы, по сути просто синтаксический сахар

2024-04-26 10:16 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var list2 = list.Where(x => x % 2 == 0);
погоди, хочу задать два встречных вопроса

что ты имеешь ввиду 
> LINQ через foreach работает

и вот это
> просто синтаксический сахар

2024-04-26 10:23 UTC, WhyRocket commented on src/MyStack/Program.cs
> +        var list = new MyLinkedList<int?>();
Это неактуальная часть программы, я её уже удалил

2024-04-26 10:26 UTC, WhyRocket commented on src/MyStack/Program.cs
> +        var list3 = list.OrderBy(item => item.Value);
Тоже неактуальная часть программы

2024-04-26 10:27 UTC, WhyRocket commented on src/MyStack/Program.cs
> +        var list3 = list.OrderBy(item => item.Value);
При выполнении заданий старался давать осмысленные названия

2024-04-26 14:37 UTC, aleksandr-goncharov requested changes

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        string[] conditionOfTask =
давай переименуем в taskConditions? мне кажется так будет лучше

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        listNew.ToConsole();
а давай вообще делать вот так:
```
list
    .Where(item => item % 2 == 1)
    .Distinct()
    .ToConsole();
```
таким образом, избежим создания переменной listNew и код будет лаконичнее
предлагаю так сделать по всех методах

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        for (int i = 0; i < 30; i++)
может откажемся от заполнения случайными строками?
а заполним список строковыми константами
просто случайная генерация строк не всегда может отражать выполненное 3 задание
например, сгенерируется 5 строк одинаковой длины и тогда мы не поймем, отработал ли OrderBy

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        for (int i = 0; i < 10; i++)
думаю, тут уместна случайная генерация
давай вынесем случайную генерацию в отдельный приватный или локальный метод
ведь такая генерация используется в нескольких участках кода (получается дублирование)

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        for (int i = 0; i < 30; i++)
заполнение случайными целочисленными значениями тоже предлагаю вынести в отдельную функцию

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        var listIndex = Enumerable.Range(0, list.Count());
это все таки не list, а просто некая коллекция (IEnumerable)
предлагаю назвать переменную indexes
и тут нужно до Count - 1 генерировать, вроде как

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            .Zip(listIndex, (val, ind) => (index: ind, value: val));
мне кажется, хорошо бы переименовать параметры лямбды
val в item (потому что везде до этого элементы списка ты назвал item)
ind в index (не нужно экономить буквы, лучше давать полные названия)

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            .Zip(listIndex, (val, ind) => (index: ind, value: val));
также принято элементы кортежа называть с большой буквы: Item и Index

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            .Where(item => !(item.index % 3 == 0))
а вот тут параметр лямбы уже не должен называться item
item - это элемент стека (судя по предыдущим методам)
тут indexedItem было бы уместно

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            .Join(list2, item1 => item1 % 10, item2 => item2 % 10, (item1, item2) => (val1: item1, val2: item2))
параметры кортежа принято называть с большой буквы

2024-04-26 14:37 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            .Join(list2, item1 => item1 % 10, item2 => item2 % 10, (item1, item2) => (val1: item1, val2: item2))
меня немного смущают нейминги переменных, но наверное тут лучше не сделать

2024-04-27 11:45 UTC, WhyRocket commented on src/MyStack/Program.cs
> +        for (int i = 0; i < 30; i++)
Часть задания заключается в том, что нужно отсортировать строки одинаковой длины

2024-04-27 16:45 UTC, WhyRocket commented on src/MyStack/Program.cs
> +        var listIndex = Enumerable.Range(0, list.Count());
Я переделал немного по-другому

2024-04-28 08:11 UTC, WhyRocket commented on src/MyStack/Program.cs
> +            .Zip(listIndex, (val, ind) => (index: ind, value: val));
Мне кажется, неправильно будет называть item, так как к отдельным значениям кортежа можно обращаться через item1, iten2 и т.д. Так как написано сейчас всё достаточно очевидно у каждого элемента коллекции есть значение и соответствующий ему индекс.
Я пытался прописать полностью, но оно как-то неочевидно стало работать далее в коде

2024-04-28 08:12 UTC, WhyRocket commented on src/MyStack/Program.cs
> +            .Zip(listIndex, (val, ind) => (index: ind, value: val));
Я перепишу, но как по мне это такая себе ошибка

2024-04-28 08:17 UTC, WhyRocket commented on src/MyStack/Program.cs
> +            .Zip(listIndex, (val, ind) => (index: ind, value: val));
Value всё-таки оставлю, потому что дальше в коде получается indexedItem.Item, что вводит в заблуждение

2024-05-02 09:53 UTC, aleksandr-goncharov submitted a review, later dismissed

2024-05-02 09:53 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +        list.FillCollection((Random) => Random.Next(30), 30);
предлагаю назвать метод расширения просто AddRange
а параметры лямбы принято называть с маленькой буквы

2024-05-06 16:12 UTC, aleksandr-goncharov requested changes

2024-05-06 16:12 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            { "1. Дана целочисленная последовательность. Извлечь из нее все нечетные числа, сохранив их исходный порядок следования и удалив все вхождения повторяющихся элементов, кроме первых.",
нужно отформатировать код инициализации массива taskConditions также, как отформатирован массив tasks

2024-05-06 16:12 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            { "1. Дана целочисленная последовательность. Извлечь из нее все нечетные числа, сохранив их исходный порядок следования и удалив все вхождения повторяющихся элементов, кроме первых.",
убрать нумерацию заданий (live sharing)

2024-05-06 16:12 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            if (Int32.TryParse(Console.ReadLine(), out int taskNumber) && taskNumber > 0 && taskNumber <= 10)
`taskNumber <= 10`
не должно быть магического числа 10 (live sharing)

2024-05-06 16:12 UTC, aleksandr-goncharov commented on src/MyStack/Program.cs
> +            .Zip(indexes, (Value, Index) => (Index, Value));
Value, Index - с маленькой буквы

2024-05-11 21:09 UTC, aleksandr-goncharov approved these changes

2024-05-11 21:09 UTC, merged